import Foundation

/// Represents a single report generated by the Large Deal Report Automation system.
struct Report: Identifiable, Codable, Hashable {
    let id: UUID
    var title: String
    var date: Date
    var summary: String
    var status: ReportStatus
    var fileSize: String
    var worksheetCount: Int
    var isFavorite: Bool
    var worksheets: [Worksheet]

    init(
        id: UUID = UUID(),
        title: String,
        date: Date,
        summary: String,
        status: ReportStatus = .pending,
        fileSize: String = "0 KB",
        worksheetCount: Int = 0,
        isFavorite: Bool = false,
        worksheets: [Worksheet] = []
    ) {
        self.id = id
        self.title = title
        self.date = date
        self.summary = summary
        self.status = status
        self.fileSize = fileSize
        self.worksheetCount = worksheetCount
        self.isFavorite = isFavorite

        // Generate default worksheets if none provided
        if worksheets.isEmpty && worksheetCount > 0 {
            self.worksheets = (1...worksheetCount).map { index in
                let names = ["Daily Data", "Main Report", "Mobile View"]
                let name = index <= names.count ? names[index - 1] : "Sheet \(index)"
                return Worksheet(name: name, rowCount: Int.random(in: 50...500), columnCount: Int.random(in: 5...20))
            }
        } else {
            self.worksheets = worksheets
        }
    }

    /// Formatted date string for display
    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        return formatter.string(from: date)
    }

    /// Short date string for compact display
    var shortDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "MMM d"
        return formatter.string(from: date)
    }

    /// Full filename as generated by the automation system
    var filename: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return "large deal report -\(formatter.string(from: date)).xlsx"
    }

    /// Whether this report is from today
    var isToday: Bool {
        Calendar.current.isDateInToday(date)
    }

    /// Whether this report is from this week
    var isThisWeek: Bool {
        Calendar.current.isDate(date, equalTo: Date(), toGranularity: .weekOfYear)
    }
}

/// Status of a report in the automation pipeline
enum ReportStatus: String, Codable, CaseIterable {
    case pending = "Pending"
    case inProgress = "In Progress"
    case completed = "Completed"
    case failed = "Failed"

    var iconName: String {
        switch self {
        case .pending: return "clock"
        case .inProgress: return "arrow.triangle.2.circlepath"
        case .completed: return "checkmark.circle.fill"
        case .failed: return "exclamationmark.triangle.fill"
        }
    }

    var color: String {
        switch self {
        case .pending: return "gray"
        case .inProgress: return "blue"
        case .completed: return "green"
        case .failed: return "red"
        }
    }
}

/// Represents a single worksheet within a report
struct Worksheet: Identifiable, Codable, Hashable {
    let id: UUID
    var name: String
    var rowCount: Int
    var columnCount: Int

    init(id: UUID = UUID(), name: String, rowCount: Int, columnCount: Int) {
        self.id = id
        self.name = name
        self.rowCount = rowCount
        self.columnCount = columnCount
    }

    var description: String {
        "\(rowCount) rows x \(columnCount) columns"
    }
}
